/************************************************************
 * Author       : KATABATHUNI BOSE
 * Project      : theroyalglow-webapp (apps/admin)
 * Module Name  : e2e/fixtures/auth
 * Scope        : Admin E2E — role auth fixtures
 *
 * Description  : Helpers that locate per-role Playwright storageState files so
 *                the RBAC E2E matrix can run as the correct seeded account
 *                (Receptionist / Owner / Developer). The session cookie is
 *                shared across `.theroyalglow.in`, so a storageState captured
 *                after signing in on the customer site (or generated by a
 *                seed/auth-setup script) is recognised by the admin subdomain.
 *
 * How to produce a state file (against a seeded environment):
 *   1. Sign in as the role on https://theroyalglow.in (Google OAuth).
 *   2. Save the browser context:  await context.storageState({ path })
 *      or run `bunx playwright codegen --save-storage=<file>`.
 *   3. Point the matching env var at the file, e.g.
 *        ADMIN_E2E_RECEPTIONIST_STATE=apps/admin/e2e/.auth/receptionist.json
 *      or drop the files in the default dir (e2e/.auth/<role>.json).
 *
 * Notes        : When a role's state file is absent the RBAC specs self-skip
 *                (see hasRoleState). This keeps the suite enumerable and
 *                typecheckable in environments without seeded accounts, while
 *                remaining fully runnable against a deployed/seeded env.
 ************************************************************/
import { existsSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const here = dirname(fileURLToPath(import.meta.url))

/** Roles exercised by the RBAC E2E matrix (Req 15.2). */
export type AdminRole = 'receptionist' | 'owner' | 'developer'

/** Default directory holding seeded storageState files (gitignored). */
const DEFAULT_STATE_DIR = process.env.ADMIN_E2E_STATE_DIR ?? join(here, '..', '.auth')

/**
 * Resolve the storageState file path for a role. An explicit
 * `ADMIN_E2E_{ROLE}_STATE` env var wins; otherwise it falls back to
 * `<stateDir>/<role>.json`.
 */
export function roleStatePath(role: AdminRole): string {
  const fromEnv = process.env[`ADMIN_E2E_${role.toUpperCase()}_STATE`]
  return fromEnv ?? join(DEFAULT_STATE_DIR, `${role}.json`)
}

/** True when a seeded storageState file exists for the role. */
export function hasRoleState(role: AdminRole): boolean {
  try {
    return existsSync(roleStatePath(role))
  } catch {
    return false
  }
}

/**
 * Customer-site origin that the admin middleware bounces unauthenticated
 * visitors to (Req 4.7 / 15.2). Configurable so local/preview runs can point
 * at a non-production origin.
 */
export const WEB_ORIGIN = process.env.ADMIN_E2E_WEB_ORIGIN ?? 'https://theroyalglow.in'

/**
 * Base URL of the customer web app used by the legacy `/admin/*` 301-redirect
 * specs (the redirect lives in apps/web middleware).
 */
export const WEB_BASE_URL = process.env.ADMIN_E2E_WEB_BASE_URL ?? 'https://theroyalglow.in'

/** Expected admin subdomain origin that the 301 redirects target (Req 15.5). */
export const ADMIN_ORIGIN = process.env.ADMIN_E2E_ADMIN_ORIGIN ?? 'https://admin.theroyalglow.in'
