-- ============================================================================
-- 0001_pg_cron_jobs.sql — Phase 6 pg_cron job functions + schedules
-- ============================================================================
--
-- HOW THIS IS APPLIED
--   This is a HAND-WRITTEN migration applied to the Neon `prod` branch at
--   DEPLOY TIME (it is NOT generated by drizzle-kit and is NOT part of the
--   drizzle journal). Run it once per environment after schema is in place:
--
--       psql "$DATABASE_URL_UNPOOLED" -f migrations/0001_pg_cron_jobs.sql
--
--   PREREQUISITE (run once by an admin on the Neon project, requires elevated
--   privileges — pg_cron is enabled per-project on Neon):
--
--       CREATE EXTENSION IF NOT EXISTS pg_cron;
--
--   All functions are CREATE OR REPLACE and all schedules use cron.schedule()
--   with a stable job name, so re-running this file is idempotent: functions
--   are replaced in place and cron.schedule() upserts the schedule for an
--   existing job name. The job bodies themselves are idempotent (ON CONFLICT
--   upserts, status-guarded UPDATEs, and the `expired:<id>` gems marker), so a
--   second run over the same data produces no additional changes.
--
-- TIMEZONE
--   Neon/Postgres runs in UTC. All cron expressions below are UTC and map to
--   IST (UTC+5:30) early-morning windows when salon traffic is zero, per
--   background-jobs.md. The job SQL that needs calendar-day boundaries converts
--   to 'Asia/Kolkata' explicitly.
--
-- COLUMN MAPPING NOTE
--   background-jobs.md Job 1 references salon/spa/membership revenue columns and
--   an `invoice_count` column that did not exist on the Phase 1
--   `daily_sales_summary` table. The real table uses `total_revenue_paise`,
--   `cash/upi/card/online_revenue_paise`, booking counters, etc. Phase 6 added
--   nullable `salon_revenue_paise`, `spa_revenue_paise`, `membership_revenue_paise`
--   (see schema/system.ts). There is NO `invoice_count` column, so it is not
--   written. The functions below map every value to the REAL column names.
-- ============================================================================


-- ----------------------------------------------------------------------------
-- Job 1 — Nightly Sales Summary  (0 18 * * * UTC = 11:30 PM IST)
-- ----------------------------------------------------------------------------
-- Aggregates the previous IST day's PAID invoices + that day's bookings into
-- one daily_sales_summary row per branch. Idempotent via the
-- (date, branch_id) unique constraint -> ON CONFLICT DO UPDATE.
--
-- Revenue split rules:
--   salon_revenue_paise      = paid service invoices on salon bookings
--   spa_revenue_paise        = paid service invoices on spa bookings
--   membership_revenue_paise = paid membership_purchase invoices
--   total_revenue_paise      = all paid invoices for the day/branch
--   <method>_revenue_paise   = paid invoices grouped by payment_method
--   discount_given_paise     = SUM(discount_amount_paise) over paid invoices
-- Booking counters are computed from `booking` rows for the same IST day.
-- ----------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION job_nightly_sales_summary() RETURNS void AS $$
  WITH target AS (
    SELECT (((NOW() AT TIME ZONE 'Asia/Kolkata')::date) - INTERVAL '1 day')::date AS ist_date
  ),
  -- Revenue side: paid invoices created on the target IST day, per branch.
  inv AS (
    SELECT
      i.branch_id,
      SUM(i.total_amount_paise)::int AS total_revenue_paise,
      SUM(CASE WHEN i.invoice_type = 'service' AND b.service_type = 'salon'
               THEN i.total_amount_paise ELSE 0 END)::int AS salon_revenue_paise,
      SUM(CASE WHEN i.invoice_type = 'service' AND b.service_type = 'spa'
               THEN i.total_amount_paise ELSE 0 END)::int AS spa_revenue_paise,
      SUM(CASE WHEN i.invoice_type = 'membership_purchase'
               THEN i.total_amount_paise ELSE 0 END)::int AS membership_revenue_paise,
      SUM(CASE WHEN i.payment_method = 'cash'   THEN i.total_amount_paise ELSE 0 END)::int AS cash_revenue_paise,
      SUM(CASE WHEN i.payment_method = 'upi'    THEN i.total_amount_paise ELSE 0 END)::int AS upi_revenue_paise,
      SUM(CASE WHEN i.payment_method = 'card'   THEN i.total_amount_paise ELSE 0 END)::int AS card_revenue_paise,
      SUM(CASE WHEN i.payment_method = 'online' THEN i.total_amount_paise ELSE 0 END)::int AS online_revenue_paise,
      SUM(i.discount_amount_paise)::int AS discount_given_paise,
      SUM(i.gems_redeemed)::int AS gems_redeemed_count
    FROM invoice i
    LEFT JOIN booking b ON i.booking_id = b.id
    CROSS JOIN target t
    WHERE i.payment_status = 'paid'
      AND (i.created_at AT TIME ZONE 'Asia/Kolkata')::date = t.ist_date
    GROUP BY i.branch_id
  ),
  -- Booking side: all bookings on the target IST day, per branch.
  bk AS (
    SELECT
      b.branch_id,
      COUNT(*)::int AS total_bookings,
      COUNT(*) FILTER (WHERE b.status = 'completed')::int AS completed_bookings,
      COUNT(*) FILTER (WHERE b.status = 'cancelled')::int AS cancelled_bookings,
      COUNT(*) FILTER (WHERE b.status = 'no_show')::int   AS no_show_bookings,
      COUNT(*) FILTER (WHERE b.is_walkin = true)::int     AS walkin_bookings
    FROM booking b
    CROSS JOIN target t
    WHERE b.booking_date = t.ist_date
    GROUP BY b.branch_id
  ),
  -- New customers: users whose first-ever booking is on the target IST day,
  -- attributed to the branch of that first booking.
  first_booking AS (
    SELECT b.customer_id, b.branch_id, b.booking_date,
           ROW_NUMBER() OVER (PARTITION BY b.customer_id ORDER BY b.created_at ASC) AS rn
    FROM booking b
  ),
  newc AS (
    SELECT fb.branch_id, COUNT(*)::int AS new_customers
    FROM first_booking fb
    CROSS JOIN target t
    WHERE fb.rn = 1 AND fb.booking_date = t.ist_date
    GROUP BY fb.branch_id
  ),
  branches AS (
    SELECT branch_id FROM inv
    UNION
    SELECT branch_id FROM bk
  )
  INSERT INTO daily_sales_summary (
    id, date, branch_id,
    total_bookings, completed_bookings, cancelled_bookings, no_show_bookings, walkin_bookings,
    total_revenue_paise, salon_revenue_paise, spa_revenue_paise, membership_revenue_paise,
    cash_revenue_paise, upi_revenue_paise, card_revenue_paise, online_revenue_paise,
    discount_given_paise, gems_redeemed_count, new_customers
  )
  SELECT
    md5(t.ist_date::text || ':' || br.branch_id),
    t.ist_date,
    br.branch_id,
    COALESCE(bk.total_bookings, 0),
    COALESCE(bk.completed_bookings, 0),
    COALESCE(bk.cancelled_bookings, 0),
    COALESCE(bk.no_show_bookings, 0),
    COALESCE(bk.walkin_bookings, 0),
    COALESCE(inv.total_revenue_paise, 0),
    COALESCE(inv.salon_revenue_paise, 0),
    COALESCE(inv.spa_revenue_paise, 0),
    COALESCE(inv.membership_revenue_paise, 0),
    COALESCE(inv.cash_revenue_paise, 0),
    COALESCE(inv.upi_revenue_paise, 0),
    COALESCE(inv.card_revenue_paise, 0),
    COALESCE(inv.online_revenue_paise, 0),
    COALESCE(inv.discount_given_paise, 0),
    COALESCE(inv.gems_redeemed_count, 0),
    COALESCE(newc.new_customers, 0)
  FROM branches br
  CROSS JOIN target t
  LEFT JOIN inv  ON inv.branch_id  = br.branch_id
  LEFT JOIN bk   ON bk.branch_id   = br.branch_id
  LEFT JOIN newc ON newc.branch_id = br.branch_id
  ON CONFLICT (date, branch_id) DO UPDATE SET
    total_bookings           = EXCLUDED.total_bookings,
    completed_bookings       = EXCLUDED.completed_bookings,
    cancelled_bookings       = EXCLUDED.cancelled_bookings,
    no_show_bookings         = EXCLUDED.no_show_bookings,
    walkin_bookings          = EXCLUDED.walkin_bookings,
    total_revenue_paise      = EXCLUDED.total_revenue_paise,
    salon_revenue_paise      = EXCLUDED.salon_revenue_paise,
    spa_revenue_paise        = EXCLUDED.spa_revenue_paise,
    membership_revenue_paise = EXCLUDED.membership_revenue_paise,
    cash_revenue_paise       = EXCLUDED.cash_revenue_paise,
    upi_revenue_paise        = EXCLUDED.upi_revenue_paise,
    card_revenue_paise       = EXCLUDED.card_revenue_paise,
    online_revenue_paise     = EXCLUDED.online_revenue_paise,
    discount_given_paise     = EXCLUDED.discount_given_paise,
    gems_redeemed_count      = EXCLUDED.gems_redeemed_count,
    new_customers            = EXCLUDED.new_customers;
$$ LANGUAGE sql;


-- ----------------------------------------------------------------------------
-- Job 2 — Membership Auto-Expire  (30 18 * * * UTC = 12:00 AM IST)
-- ----------------------------------------------------------------------------
-- Flips active memberships to expired once their expiry has passed.
-- Idempotent: a second run matches zero rows (status already 'expired').
-- ----------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION job_membership_auto_expire() RETURNS void AS $$
  UPDATE spa_membership
  SET status = 'expired', updated_at = NOW()
  WHERE status = 'active'
    AND expires_at < NOW();
$$ LANGUAGE sql;


-- ----------------------------------------------------------------------------
-- Job 3 — Offer Auto-Expire  (35 18 * * * UTC = 12:05 AM IST)
-- ----------------------------------------------------------------------------
-- Deactivates offers whose end_date has passed. end_date is a DATE column, so
-- compare against the current IST calendar date. Idempotent: a second run
-- matches zero rows (is_active already false).
-- ----------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION job_offer_auto_expire() RETURNS void AS $$
  UPDATE offer
  SET is_active = false, updated_at = NOW()
  WHERE is_active = true
    AND end_date < (NOW() AT TIME ZONE 'Asia/Kolkata')::date;
$$ LANGUAGE sql;


-- ----------------------------------------------------------------------------
-- Job 4 — Session Cleanup  (0 21 * * 0 UTC = 2:30 AM IST Sunday)
-- ----------------------------------------------------------------------------
-- Deletes expired Better Auth session rows. Table/column verified against
-- schema/auth.ts: table "session", column "expires_at". Idempotent: a second
-- run deletes zero rows.
-- ----------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION job_session_cleanup() RETURNS void AS $$
  DELETE FROM session
  WHERE expires_at < NOW();
$$ LANGUAGE sql;


-- ----------------------------------------------------------------------------
-- Job 6 — Monthly GST Summary  (30 19 1 * * UTC = 1:00 AM IST on the 1st)
-- ----------------------------------------------------------------------------
-- Aggregates the PREVIOUS month's paid service + membership_purchase invoices
-- into monthly_gst_summary. `month` is stored as TEXT 'YYYY-MM' (the schema's
-- unique column). Idempotent via ON CONFLICT (month) DO UPDATE.
-- ----------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION job_monthly_gst_summary() RETURNS void AS $$
  WITH target AS (
    SELECT
      -- Previous month, anchored to IST calendar.
      to_char(
        (date_trunc('month', (NOW() AT TIME ZONE 'Asia/Kolkata')) - INTERVAL '1 month'),
        'YYYY-MM'
      ) AS month_key
  ),
  agg AS (
    SELECT
      t.month_key,
      COALESCE(SUM(i.taxable_value_paise), 0)::int AS taxable_value_paise,
      COALESCE(SUM(i.gst_amount_paise), 0)::int    AS gst_amount_paise,
      COUNT(*)::int                                AS invoice_count
    FROM invoice i
    CROSS JOIN target t
    WHERE i.payment_status = 'paid'
      AND i.invoice_type IN ('service', 'membership_purchase')
      AND to_char((i.created_at AT TIME ZONE 'Asia/Kolkata'), 'YYYY-MM') = t.month_key
    GROUP BY t.month_key
  )
  INSERT INTO monthly_gst_summary (id, month, taxable_value_paise, gst_amount_paise, invoice_count, sac_code)
  SELECT
    md5(month_key),
    month_key,
    taxable_value_paise,
    gst_amount_paise,
    invoice_count,
    '999721'
  FROM agg
  ON CONFLICT (month) DO UPDATE SET
    taxable_value_paise = EXCLUDED.taxable_value_paise,
    gst_amount_paise    = EXCLUDED.gst_amount_paise,
    invoice_count       = EXCLUDED.invoice_count,
    sac_code            = EXCLUDED.sac_code;
$$ LANGUAGE sql;


-- ----------------------------------------------------------------------------
-- Job 7 — Gems Auto-Expire  (40 18 * * * UTC = 12:10 AM IST)
-- ----------------------------------------------------------------------------
-- For each EARNED loyalty_transaction whose gems have expired and which has not
-- already been offset, insert one offsetting 'expired' transaction
-- (gems_amount = -original) marked `expired:<txId>` and decrement the owning
-- loyalty_account.gems_balance by the same amount.
--
-- Idempotency: the `expired:<txId>` description marker. A transaction that
-- already has a matching 'expired' offset row is skipped, so re-running affects
-- nothing. Implemented in PL/pgSQL so the offset INSERT and the balance
-- decrement happen together per account within the function's transaction.
-- ----------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION job_gems_auto_expire() RETURNS void AS $$
DECLARE
  rec RECORD;
BEGIN
  FOR rec IN
    SELECT lt.id, lt.loyalty_account_id, lt.gems_amount
    FROM loyalty_transaction lt
    WHERE lt.type = 'earned'
      AND lt.gems_amount > 0
      AND lt.expires_at IS NOT NULL
      AND lt.expires_at < NOW()
      AND NOT EXISTS (
        SELECT 1 FROM loyalty_transaction lt2
        WHERE lt2.type = 'expired'
          AND lt2.description = 'expired:' || lt.id
      )
  LOOP
    INSERT INTO loyalty_transaction (id, loyalty_account_id, type, gems_amount, description, created_at)
    VALUES (md5('expired:' || rec.id), rec.loyalty_account_id, 'expired', -rec.gems_amount, 'expired:' || rec.id, NOW());

    UPDATE loyalty_account
    SET gems_balance = gems_balance - rec.gems_amount, updated_at = NOW()
    WHERE id = rec.loyalty_account_id;
  END LOOP;
END;
$$ LANGUAGE plpgsql;


-- ============================================================================
-- Schedule registration
-- ----------------------------------------------------------------------------
-- cron.schedule(job_name, schedule, command) upserts by job_name, so re-running
-- this block simply re-points each named job at the (replaced) function. All
-- expressions are UTC; the IST equivalent is noted alongside each.
-- ============================================================================
SELECT cron.schedule('nightly-sales-summary', '0 18 * * *',   $$ SELECT job_nightly_sales_summary(); $$); -- 11:30 PM IST daily
SELECT cron.schedule('membership-auto-expire', '30 18 * * *', $$ SELECT job_membership_auto_expire(); $$); -- 12:00 AM IST daily
SELECT cron.schedule('offer-auto-expire',      '35 18 * * *', $$ SELECT job_offer_auto_expire(); $$);      -- 12:05 AM IST daily
SELECT cron.schedule('gems-auto-expire',       '40 18 * * *', $$ SELECT job_gems_auto_expire(); $$);       -- 12:10 AM IST daily
SELECT cron.schedule('session-cleanup',        '0 21 * * 0',  $$ SELECT job_session_cleanup(); $$);        -- 2:30 AM IST Sunday
SELECT cron.schedule('monthly-gst-summary',    '30 19 1 * *', $$ SELECT job_monthly_gst_summary(); $$);    -- 1:00 AM IST on the 1st


-- ============================================================================
-- Job 5 — pprd DB Sync (NOT scheduled here)
-- ----------------------------------------------------------------------------
-- Job 5 runs via GitHub Actions cron (Phase 9 CI/CD), which resets the Neon
-- `pprd` branch from `prod` and then applies the anonymisation SQL below ON
-- THE PPRD BRANCH ONLY. It is intentionally NOT registered with cron.schedule
-- and is shown here for reference so the anonymisation logic lives with the
-- other job SQL. DO NOT run this against the `prod` (production) branch — it
-- destroys real customer PII.
--
--   -- Anonymise copied customer data on the pprd branch:
--   UPDATE customer_profile SET
--     phone        = 'XXXXX' || RIGHT(phone, 5),
--     utm_campaign = NULL,
--     utm_source   = NULL;
--
--   UPDATE "user" SET
--     email = 'anon_' || id || '@dev.theroyalglow.in',
--     name  = 'Test User ' || SUBSTRING(id, 1, 6);
-- ============================================================================
