/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
    'payload-mcp-api-keys': PayloadMcpApiKeyAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    blog: Blog;
    gallery: Gallery;
    team: Team;
    banner: Banner;
    faq: Faq;
    testimonial: Testimonial;
    offer: Offer;
    'service-card': ServiceCard;
    service_category: ServiceCategory;
    service: Service;
    'payload-mcp-api-keys': PayloadMcpApiKey;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    blog: BlogSelect<false> | BlogSelect<true>;
    gallery: GallerySelect<false> | GallerySelect<true>;
    team: TeamSelect<false> | TeamSelect<true>;
    banner: BannerSelect<false> | BannerSelect<true>;
    faq: FaqSelect<false> | FaqSelect<true>;
    testimonial: TestimonialSelect<false> | TestimonialSelect<true>;
    offer: OfferSelect<false> | OfferSelect<true>;
    'service-card': ServiceCardSelect<false> | ServiceCardSelect<true>;
    service_category: ServiceCategorySelect<false> | ServiceCategorySelect<true>;
    service: ServiceSelect<false> | ServiceSelect<true>;
    'payload-mcp-api-keys': PayloadMcpApiKeysSelect<false> | PayloadMcpApiKeysSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User | PayloadMcpApiKey;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
export interface PayloadMcpApiKeyAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  prefix?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    hero?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blog".
 */
export interface Blog {
  id: number;
  title: string;
  /**
   * Auto-generated from the title; kebab-case. Editable.
   */
  slug: string;
  /**
   * Used in the listing and as the meta-description fallback (≤ 200 chars recommended).
   */
  excerpt: string;
  coverImage?: (number | null) | Media;
  body: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  author?: (number | null) | Team;
  category?: ('skincare' | 'hair' | 'spa' | 'bridal' | 'tips') | null;
  tags?: string[] | null;
  seo?: {
    metaTitle?: string | null;
    metaDescription?: string | null;
    ogImage?: (number | null) | Media;
  };
  /**
   * Required when published; controls listing order.
   */
  publishedAt?: string | null;
  status: 'draft' | 'published';
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "team".
 */
export interface Team {
  id: number;
  name: string;
  role: string;
  bio?: string | null;
  photo?: (number | null) | Media;
  specializations?:
    | {
        value: string;
        id?: string | null;
      }[]
    | null;
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "gallery".
 */
export interface Gallery {
  id: number;
  image: number | Media;
  alt: string;
  caption?: string | null;
  category?: ('salon' | 'spa' | 'interior' | 'team' | 'work') | null;
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "banner".
 */
export interface Banner {
  id: number;
  headline: string;
  image: number | Media;
  ctaLabel?: string | null;
  /**
   * Internal path or absolute URL.
   */
  ctaHref?: string | null;
  active: boolean;
  startAt?: string | null;
  endAt?: string | null;
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faq".
 */
export interface Faq {
  id: number;
  question: string;
  /**
   * Answer-first phrasing per the SEO guidelines.
   */
  answer: string;
  category?: ('booking' | 'pricing' | 'services' | 'policies') | null;
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Customer reviews displayed on the homepage carousel.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonial".
 */
export interface Testimonial {
  id: number;
  reviewerName: string;
  rating: number;
  /**
   * Keep to 2–3 sentences for best display.
   */
  reviewText: string;
  /**
   * Displayed as-is. E.g. "1 week ago", "1 month ago".
   */
  timeLabel?: string | null;
  active?: boolean | null;
  /**
   * Lower numbers appear first in the carousel.
   */
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Promotional offer cards shown on homepage and /offers page.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "offer".
 */
export interface Offer {
  id: number;
  /**
   * E.g. "20% OFF All Facials — This week only!"
   */
  title: string;
  /**
   * 1-2 lines shown on the offer card.
   */
  description?: string | null;
  /**
   * E.g. "20% OFF", "₹500 off", "Buy 2 Get 1 Free". Shown as a badge.
   */
  discountLabel?: string | null;
  image: number | Media;
  ctaLabel?: string | null;
  /**
   * Internal path or full URL. Default opens the booking dialog.
   */
  ctaHref?: string | null;
  category?: ('all' | 'salon' | 'spa' | 'bridal' | 'nails' | 'skincare') | null;
  active: boolean;
  /**
   * Leave blank to show immediately.
   */
  validFrom?: string | null;
  /**
   * Leave blank for no expiry. Web app filters by this date.
   */
  validUntil?: string | null;
  /**
   * Lower numbers appear first.
   */
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Homepage service category cards (Hair, Spa, Bridal, Nails, etc.).
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "service-card".
 */
export interface ServiceCard {
  id: number;
  /**
   * E.g. "Hair", "Spa", "Bridal"
   */
  name: string;
  /**
   * Display string shown on the card. E.g. "₹500", "₹1,499"
   */
  fromPrice: string;
  image: number | Media;
  /**
   * Descriptive text for screen readers and SEO.
   */
  imageAlt?: string | null;
  /**
   * Where the "Book →" button links. Use anchor IDs like /services#spa.
   */
  bookingHref: string;
  active?: boolean | null;
  /**
   * Lower numbers appear first in the scroll row.
   */
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Bookable service categories. Categories are DEACTIVATED (untick "Active"), never deleted — that is why there is no delete button. A category's Salon/SPA type governs which services can belong to it, and a booking may only contain services of one type.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "service_category".
 */
export interface ServiceCategory {
  id: string;
  /**
   * E.g. "Hair Care", "Body Massage", "Bridal".
   */
  name: string;
  /**
   * URL-safe identifier. Generated from the name if left blank.
   */
  slug: string;
  /**
   * Optional. Shown to customers alongside the category.
   */
  description?: string | null;
  /**
   * Governs which services belong here. A booking is Salon OR SPA, never mixed.
   */
  serviceType: 'salon' | 'spa';
  /**
   * Lower numbers appear first in the booking dialog and /services page.
   */
  displayOrder?: number | null;
  /**
   * Untick to retire this category. This replaces deletion.
   */
  isActive?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Bookable services synced to the booking engine. Services are DEACTIVATED, never deleted — untick "Active" to retire one. There is intentionally no delete button, because past bookings and invoices reference these records.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "service".
 */
export interface Service {
  id: string;
  categoryId: string | ServiceCategory;
  name: string;
  /**
   * Auto-generated from the service name on create. Override only if needed.
   */
  slug: string;
  description?: string | null;
  /**
   * Typical: beard/shave 15min, haircut 30min, advanced haircut / classic facial / spa mani-pedi 45min, most SPA 60-90min, global colour (long) & bridal makeup 120min, keratin 180min.
   */
  durationMinutes: '15' | '30' | '45' | '60' | '90' | '120' | '150' | '180';
  /**
   * Clean-up/turnaround time reserved after the service.
   */
  bufferMinutes?: number | null;
  /**
   * GST-inclusive price in paise (e.g. 149900 = ₹1,499).
   */
  pricePaise: number;
  /**
   * Untick to retire a service. This replaces deletion.
   */
  isActive?: boolean | null;
  imageUrl?: string | null;
  /**
   * Lower numbers appear first within the category.
   */
  displayOrder?: number | null;
  gemsRedeemable?: boolean | null;
  /**
   * Required when "Redeemable with Gems" is enabled. Must be greater than 0.
   */
  gemsRequired?: number | null;
  /**
   * Position in the gems redemption catalogue.
   */
  gemsCatalogueOrder?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * API keys control which collections, resources, tools, and prompts MCP clients can access
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-mcp-api-keys".
 */
export interface PayloadMcpApiKey {
  id: number;
  /**
   * The user that the API key is associated with.
   */
  user: number | User;
  /**
   * A useful label for the API key.
   */
  label?: string | null;
  /**
   * The purpose of the API key.
   */
  description?: string | null;
  service?: {
    /**
     * Allow clients to find service.
     */
    find?: boolean | null;
  };
  serviceCategory?: {
    /**
     * Allow clients to find service_category.
     */
    find?: boolean | null;
  };
  serviceCard?: {
    /**
     * Allow clients to find service-card.
     */
    find?: boolean | null;
  };
  blog?: {
    /**
     * Allow clients to find blog.
     */
    find?: boolean | null;
  };
  gallery?: {
    /**
     * Allow clients to find gallery.
     */
    find?: boolean | null;
  };
  team?: {
    /**
     * Allow clients to find team.
     */
    find?: boolean | null;
  };
  banner?: {
    /**
     * Allow clients to find banner.
     */
    find?: boolean | null;
  };
  faq?: {
    /**
     * Allow clients to find faq.
     */
    find?: boolean | null;
  };
  testimonial?: {
    /**
     * Allow clients to find testimonial.
     */
    find?: boolean | null;
  };
  offer?: {
    /**
     * Allow clients to find offer.
     */
    find?: boolean | null;
  };
  media?: {
    /**
     * Allow clients to find media.
     */
    find?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
  enableAPIKey?: boolean | null;
  apiKey?: string | null;
  apiKeyIndex?: string | null;
  collection: 'payload-mcp-api-keys';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'blog';
        value: number | Blog;
      } | null)
    | ({
        relationTo: 'gallery';
        value: number | Gallery;
      } | null)
    | ({
        relationTo: 'team';
        value: number | Team;
      } | null)
    | ({
        relationTo: 'banner';
        value: number | Banner;
      } | null)
    | ({
        relationTo: 'faq';
        value: number | Faq;
      } | null)
    | ({
        relationTo: 'testimonial';
        value: number | Testimonial;
      } | null)
    | ({
        relationTo: 'offer';
        value: number | Offer;
      } | null)
    | ({
        relationTo: 'service-card';
        value: number | ServiceCard;
      } | null)
    | ({
        relationTo: 'service_category';
        value: string | ServiceCategory;
      } | null)
    | ({
        relationTo: 'service';
        value: string | Service;
      } | null)
    | ({
        relationTo: 'payload-mcp-api-keys';
        value: number | PayloadMcpApiKey;
      } | null);
  globalSlug?: string | null;
  user:
    | {
        relationTo: 'users';
        value: number | User;
      }
    | {
        relationTo: 'payload-mcp-api-keys';
        value: number | PayloadMcpApiKey;
      };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user:
    | {
        relationTo: 'users';
        value: number | User;
      }
    | {
        relationTo: 'payload-mcp-api-keys';
        value: number | PayloadMcpApiKey;
      };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  prefix?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        hero?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blog_select".
 */
export interface BlogSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  excerpt?: T;
  coverImage?: T;
  body?: T;
  author?: T;
  category?: T;
  tags?: T;
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        ogImage?: T;
      };
  publishedAt?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "gallery_select".
 */
export interface GallerySelect<T extends boolean = true> {
  image?: T;
  alt?: T;
  caption?: T;
  category?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "team_select".
 */
export interface TeamSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  bio?: T;
  photo?: T;
  specializations?:
    | T
    | {
        value?: T;
        id?: T;
      };
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "banner_select".
 */
export interface BannerSelect<T extends boolean = true> {
  headline?: T;
  image?: T;
  ctaLabel?: T;
  ctaHref?: T;
  active?: T;
  startAt?: T;
  endAt?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faq_select".
 */
export interface FaqSelect<T extends boolean = true> {
  question?: T;
  answer?: T;
  category?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonial_select".
 */
export interface TestimonialSelect<T extends boolean = true> {
  reviewerName?: T;
  rating?: T;
  reviewText?: T;
  timeLabel?: T;
  active?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "offer_select".
 */
export interface OfferSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  discountLabel?: T;
  image?: T;
  ctaLabel?: T;
  ctaHref?: T;
  category?: T;
  active?: T;
  validFrom?: T;
  validUntil?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "service-card_select".
 */
export interface ServiceCardSelect<T extends boolean = true> {
  name?: T;
  fromPrice?: T;
  image?: T;
  imageAlt?: T;
  bookingHref?: T;
  active?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "service_category_select".
 */
export interface ServiceCategorySelect<T extends boolean = true> {
  id?: T;
  name?: T;
  slug?: T;
  description?: T;
  serviceType?: T;
  displayOrder?: T;
  isActive?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "service_select".
 */
export interface ServiceSelect<T extends boolean = true> {
  id?: T;
  categoryId?: T;
  name?: T;
  slug?: T;
  description?: T;
  durationMinutes?: T;
  bufferMinutes?: T;
  pricePaise?: T;
  isActive?: T;
  imageUrl?: T;
  displayOrder?: T;
  gemsRedeemable?: T;
  gemsRequired?: T;
  gemsCatalogueOrder?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-mcp-api-keys_select".
 */
export interface PayloadMcpApiKeysSelect<T extends boolean = true> {
  user?: T;
  label?: T;
  description?: T;
  service?:
    | T
    | {
        find?: T;
      };
  serviceCategory?:
    | T
    | {
        find?: T;
      };
  serviceCard?:
    | T
    | {
        find?: T;
      };
  blog?:
    | T
    | {
        find?: T;
      };
  gallery?:
    | T
    | {
        find?: T;
      };
  team?:
    | T
    | {
        find?: T;
      };
  banner?:
    | T
    | {
        find?: T;
      };
  faq?:
    | T
    | {
        find?: T;
      };
  testimonial?:
    | T
    | {
        find?: T;
      };
  offer?:
    | T
    | {
        find?: T;
      };
  media?:
    | T
    | {
        find?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  enableAPIKey?: T;
  apiKey?: T;
  apiKeyIndex?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}